### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by andrewliao11** [yu4u/dnn-watermark#3]
Hi @yu4u 
I post my question to the paper here since the email address on your other paper seems to be deprecated.

I just read your paper: Embedding Watermarks into Deep Neural Networks, which looks deep neural network from a special perspective! 
I have one question about the potential attack type (related 2.3):
I think there is still one missing attack type: distillation. Distillation is a valid attack type since the goal of the attacker is to wipe out the watermark and get the model at the same time. Here, the model is not restricted to the original model, it can be different model with the similar performance. Since the distillation will modify the model parameters, it seems that there is no guarantees that the distilled model will contains the watermark embedded in the original models.
Please correct me if I’m wrong since I’m quite new to this field :)

Best regards, 
Yuan-Hong Liao

**Comment by yu4u** [comment]
Thank you for your interest in our work!
Your comment that watermarks would disappear by distillation is completely correct.
However, I think it is not so important because distillation requires many training data in the same domain as the training data used in training the teacher model.

**Comment by andrewliao11** [comment]
Thanks for the reply!
