### ISSUE TITLE
Explanation for watermark regularizer

### ISSUE THREAD

**Issue by SindujaPrakash** [yu4u/dnn-watermark#4]
Hi, I am a graduate student preparing for my master thesis. I am interested in using your watermark regularizer to test its performance in embedded conditions. Could you explain me in depth about the logic behind the watermark regularizer. It would be of great help ! Thanks

**Comment by yu4u** [comment]
Thank you for being interested in our work.
Please refer to our paper for technical details.

https://arxiv.org/abs/1701.04082

**Comment by SindujaPrakash** [comment]
Hi ! Thank you for the response. I have read the paper. I do not understand the sigmoid function that you use while extracting the watermark. Could you explain it in detail !?

**Comment by yu4u** [comment]
The sigmoid function is used only in embedding the watermark.
In extracting the watermark simple step function is used as Eq. (2).
