### ISSUE TITLE
Overflow bug  on extract the embedded watermark

### ISSUE THREAD

**Issue by kaidi-jin** [yu4u/dnn-watermark#7]
I operate it with the default  command 

In the  train time :
     python train_wrn.py config/train_random_min.json
and  the result is:
![image](https://user-images.githubusercontent.com/34271351/54532998-27b37200-49c4-11e9-95ac-d96ad8e4aaee.png)
But In the extract the embedded watermark time:
get the wrong is that:
![image](https://user-images.githubusercontent.com/34271351/54533182-8e389000-49c4-11e9-92b0-752353066408.png)

My experimental environment is under docker  with  tensorflow-cpu (some thing wrong with tensorflow-gpu  like: could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR Check failed: stream->parent() >GetConvolveAlgorithms(&algorithms) )

By the way, I think the requirement environment should be mentioned in the ReadMe.  It cost me a lot of time on install hdf5 and table python-dev

Can  someone have idea? Thank you very much!

**Comment by yu4u** [comment]
https://stackoverflow.com/questions/47044541/how-to-avoid-an-overflow-in-numpy-exp

**Comment by kaidi-jin** [comment]
@yu4u ，  thank you for your advice , It works.   I will  keep study the paper and this interesting work.
